### ISSUE TITLE
Relating feature values in search templates

### ISSUE THREAD

**Issue by dirkroorda** [annotation/text-fabric#10]
Currently, when writing search templates you cannot express that the value of one feature on on node
is equal to the value of another feature on another node.

For example, you might want to look for clauses in which the verb in a Pred phrase has the same
number as the noun in a Subj phrase. Let's do it only for 1-word Pred and Sunj phrases.

```
clause
  phrase function=Pred
    =: v:word pdp=verb
    :=
  phrase function=Subj
    =: s:word pdp=subs nu=v.nu
    :=
```

The bit `nu=v.nu` is not possible currently.

We also would like to be able to say in the template above

```
s.gn = v.gn
```

(`gn` is the gender feature).
This is also not supported yet.

It would be nice to have both syntaxes working in TF search.

**Comment by codykingham** [comment]
This would be a fantastic addition, which would allow for searches for subject/verb agreement, for instance.

**Comment by dirkroorda** [comment]
It has been reissued in #50 and implemented.
