### ISSUE TITLE
Add cutoff indicator for end=

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#40]
It would be nice if `end=` also produced a statement similar to `pd.Dataframes` when a df extends beyond the limit, e.g. "22 more results not shown" or something like this. But this may be too minor to warrant addition. Feel free to ignore.

**Comment by dirkroorda** [comment]
Technically, you may feed the `table()` and `show()` functions an arbitrary iterable, so the number of items is not always known. If the argument comes from `A.search()` then we know the amount of items. But so do you. If you ask TF to report it, there are a few ramifications. In plain text, HTML, or Markdown? Is the function called inside a Jupyter notebook or from the TF browser? What is the best wording? I feel these things are better left to the user of TF for the moment.
