### ISSUE TITLE
Clearer Browser Search Icons

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#41]
The current browser search icons are a bit confusing (recycle sign and gear). In demo'ing TF to several people this has caused some confusion. A google search for "search icon" gives results for magnifying glasses instead. I think this would be a better fit.

**Comment by dirkroorda** [comment]
I will change them to the usual search icon for the next release of TF: [search](https://fontawesome.com/icons/search?style=solid)

**Comment by dirkroorda** [comment]
Done
