### ISSUE TITLE
Converters

### ISSUE THREAD

**Issue by dirkroorda** [annotation/text-fabric#45]
TF can import from and export to XML.

It is desirable that TF can import corpora from other formats as easily as possible.

Yet, input formats differ widely.

Make an intermediate format that TF can consume and that is easy to generate from e.g. TEI, other XML and other database formats.

Write an import module for this intermediate format.

**Comment by dirkroorda** [comment]
For example, the intermediate format could be the form of a stream of events, where each event consists of:

1. a node type (word, sentence, phrase, chapter)
2. a sequence number *within* the node type
3. a dict of features and values for this node
4. a tuple of surrounding (nodeType, sequence number) nodes, but only if the current node is a slot node

TF can then glue the events together into a valid TF source.

**Comment by dirkroorda** [comment]
The order of the events is not important.
The exact values of the sequence numbers are not important, they are only needed to point at things.

Multiple events for the same node are allowed: 

* the features of a later event merge with the features of previous events, and in case of conflicting values, later events win.
* the surrounding nodes tuples will add up across events and duplicates will be weeded out.


TF will first collect all events, and then renumber everything the TF way.

**Comment by dirkroorda** [comment]
So, if your source is a TEI file, you can recursively walk through all body elements.

For elements that enclose <w> elements, you fire events of the form

(element name, element sequence number, attributes of element)

and for <w> elements you fire events of the form

(word, word sequence number, attributes of word, (elem name, sequence number for all surrounding elements))

**Comment by ernstboogert** [comment]
Hi Dirk, how would you parse something like this test xml:

<a>
	<b>This is a <c>beautiful </c> test <add>round</add>for <milestone unit="subsection" n="4"/> convertors.</b>
    <b>And this is another <c>surprise...</c></b>
</a>

**Comment by ernstboogert** [comment]
So 'b' is the basic text that needs to be numbered from 1 onwards. 'C' and 'add' are additions to the text that need to be mapped to the word they follow. And 'milestone' is another type of feature that needs to be added as a feature to the word that it follows...

**Comment by dirkroorda** [comment]
As to milestone: I would make nodes for the chunks between milestones, e.g. subsection nodes here.

As to add and c:I would just leave the material in these elements in the text, but make new node types, add nodes and c nodes for them.

**Comment by dirkroorda** [comment]
The token converter has been developed into tf.convert.walker.py and has been used for the conversion of Old Babylonian, the Quran, the Dead Sea Scrolls and Patristic Literature (the last one by Ernst Boogert).
