### ISSUE TITLE
Comments starting after whitespace

### ISSUE THREAD

**Issue by camilstaps** [annotation/text-fabric#52]
I know the documentation says that "you cannot comment out parts of lines, only whole lines", and understand that allowing `%` after text could lead to ambiguity, but would it be possible to allow whitespace before `%`? This would allow you to comment on parts of a query without obscuring the indentation structure. Essentially I'd propose to use the regular expression `^\s*(%|$)` to strip comments (this also checks for whitespace-only lines).

**Comment by dirkroorda** [comment]
Good point. Nice suggestion as how to implement it. Will be in the next release.
