### ISSUE TITLE
Update Software Heritage badge

### ISSUE THREAD

**Issue by moranegg** [annotation/text-fabric#54]
Hello @dirkroorda,
At Software Heritage we really liked your idea of putting a SWH badge on the README.
We liked it so much that we created three types of badges that you can find on the permalink tab on the right :-)

The archived repository badge:[![SWH](https://archive.softwareheritage.org/badge/origin/https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/browse/origin/https://github.com/annotation/text-fabric/)
Coded with:
`[![SWH](https://archive.softwareheritage.org/badge/origin/https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/browse/origin/https://github.com/annotation/text-fabric/)`

The archived release badge: [![SWH](https://archive.softwareheritage.org/badge/swh:1:rel:4f61758988dfa0479b69f790f2f857738574e3e8;origin=https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/swh:1:rel:4f61758988dfa0479b69f790f2f857738574e3e8;origin=https://github.com/annotation/text-fabric/)
Coded with:
`[![SWH](https://archive.softwareheritage.org/badge/swh:1:rel:4f61758988dfa0479b69f790f2f857738574e3e8;origin=https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/swh:1:rel:4f61758988dfa0479b69f790f2f857738574e3e8;origin=https://github.com/annotation/text-fabric/)`

And the badges to a specific artifact identified with the swh-id,
for example a snapshot with all branches and releases captured in April 2019: [![SWH](https://archive.softwareheritage.org/badge/swh:1:snp:1de172a10590eed2f1e3dcd049f13b4ed7d72bd0;origin=https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/swh:1:snp:1de172a10590eed2f1e3dcd049f13b4ed7d72bd0;origin=https://github.com/annotation/text-fabric/)
Coded with:
`[![SWH](https://archive.softwareheritage.org/badge/swh:1:snp:1de172a10590eed2f1e3dcd049f13b4ed7d72bd0;origin=https://github.com/annotation/text-fabric/)](https://archive.softwareheritage.org/swh:1:snp:1de172a10590eed2f1e3dcd049f13b4ed7d72bd0;origin=https://github.com/annotation/text-fabric/)`

Hope you like the result.
Cheers,
Morane

**Comment by dirkroorda** [comment]
Hi Morane,
As always with SH: you do more than expected! I'll put the badges in place very soon!
Many thanks.
And lots of success!
