### ISSUE TITLE
Less results with less restrictive query

### ISSUE THREAD

**Issue by camilstaps** [annotation/text-fabric#56]
The following search on the BHSA app gives 617 results:

```
clause
  phrase typ=PP function=Adju
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```

When I add a `prep` node I get 696 results:

```
clause
  phrase typ=PP function=Adju
    word sp=prep
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```

I would expect the second query to give less or equally many results as the first, or do I overlook something?

**Comment by codykingham** [comment]
Hi @camilstaps , this is probably a question we should transfer to eith github.com/etcbc/bhsa or github.com/annotation/text-methods

The answer, though, is that you are finding Adju PP phrases that contain more than 1 preposition. So `word sp=prep` matches multiple terms. Thus you get more results.

**Comment by camilstaps** [comment]
@codykingham I see now, that makes sense. Thanks for the explanation!

I posted here because I thought it may point to a bug in TF, but it isn't, of course :)
