### ISSUE TITLE
feature request: plain text show

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#58]
In many searches, the structure of the underlying linguistic units is not of interest. 

It would be nice to have an option for the show function to instead show text using the new `plain` function rather than `pretty`. That is especially useful for corpora like BHSA or NENA that have a lot of objects which end up crowding the screen in `pretty` show. A `plain` show would let you scan through results more efficiently.

**Comment by dirkroorda** [comment]
We have that: `table()` is the plain equivalent of `show()`.
Moreover, even in `show()` you can reduce the level of detail by passing `baseTypes="phrase"` for example. `pretty()`, `prettyTuple()` and `show()` will unravel the structure until they encounter nodes in one of the baseTypes, and from there they switch to `plain`.

**Comment by codykingham** [comment]
But does this work in the browser? for instance, when I run a browser query, I have to wade through all of the boxes. But with most search tools (e.g. Accordance) I get a simple text with highlighting

**Comment by dirkroorda** [comment]
Yes, it also works in the browser. All those options, like condenseTypes, baseTypes, standardFeatures, queryFeatures work there.

Query results are presented with `table()`. If you click the triangle of an individual result, you get the `pretty()` of that result.
