### ISSUE TITLE
combining /with/ and relation operators .lex=lex.  is not possible

### ISSUE THREAD

**Issue by oliverglanz** [annotation/text-fabric#62]
**Problem**
It is not possible to define the lex relation between words that are defined by a containment operators:
```
/with/
  example
/-/
```
The following examples shows such a case:

![Annotation 2020-09-26 132541](https://user-images.githubusercontent.com/8409738/94346614-ce39f380-fffb-11ea-85bb-c36efebf0198.png)

This might be a bug or presently not possible. If the latter is the case, then the error description

```line 15: Relation with undefined name: "w2"```
 is misleading and needs to be changed.

**Comment by dirkroorda** [comment]
You are correct that this is not yet possible. And also that the error message is not very helpful.

That said, the docs indicate that there are restrictions in the use of names of quantifiers:

https://annotation.github.io/text-fabric/about/searchusage.html#restrictions

But these restrictions are stated in difficult language.

A bit later the reasons why are explained: https://annotation.github.io/text-fabric/about/searchusage.html#implementation

**Comment by dirkroorda** [comment]
It is a pity that the kind of query that you give here as an example is not supoorted by Text-Fabric.

It would make the query language much more expressive.
Unfortunately, I do not know at the moment how to implement that in full generality, and then the challenge is to implement it efficiently as well.

**Comment by dirkroorda** [comment]
However, you could also remove the /with/ and /-/ from your query.
In this case you get what you want.

Indeed, there are other cases where what you point out here is a real limitation.

**Comment by oliverglanz** [comment]
> You are correct that this is not yet possible. And also that the error message is not very helpful.
> 
> That said, the docs indicate that there are restrictions in the use of names of quantifiers:
> 
> https://annotation.github.io/text-fabric/about/searchusage.html#restrictions
> 
> But these restrictions are stated in difficult language.
> 
> A bit later the reasons why are explained: https://annotation.github.io/text-fabric/about/searchusage.html#implementation

**Comment by oliverglanz** [comment]
Ok. It seems that TF has the same limitations as MQL's "UnorderedGroup" it is also not possible to use the "AS" operator for elements within "UnorderedGroup". 

And yes, I am aware that I could have written the query without ```/where/ - /-/``` but sometimes it is necessary to use this if there are other object types involved whose relation to each other need to be defined.

**Comment by dirkroorda** [comment]
For those cases, you could run a relaxed query and then filter out the unwanted results by a snippet of Python code, e.g.

```
results = [r for r in A.search(relaxedQuery) if r[3] == r[5]]
```

In TF queries are a way to circumvent a lot of Python programming, but it is not the exclusive way to get at your data, as in SQL or MySQL.

There is a balancing act between wrestling with the query language and hand-coding.
