### ISSUE TITLE
Use of Python 3.8 method breaks backwards compatibility by using removeprefix()

### ISSUE THREAD

**Issue by jamespstrachan** [annotation/text-fabric#72]
Commit 6d48063a73783de6e8113db911aacc15911a6f36 uses new Python 3.8 method `removeprefix()` and in doing so breaks compatibility with older Python versions for no benefit I can see. 

The Python 3.x method `lstrip('v')` would have the same effect, so: 
````
r = latestR[1:] if latestR.startswith("v") else latestR
# becomes
r = latestR.lstrip("v")
# not
r = latestR.removeprefix("v")
````

https://github.com/annotation/text-fabric/commit/6d48063a73783de6e8113db911aacc15911a6f36#diff-dd0a4a8daf89527a68b587288aa973a3ef5775c72a51f2e4e54b642fc5a4df06L513

**Comment by dirkroorda** [comment]
As far as I can see, `removeprefix` does not occur anymore in Text-Fabric.

**Comment by jamespstrachan** [comment]
You're right! I was confused by the bump in required Python version to 3.8
in that commit linked above and read the change the wrong way round.

Is there something in that changeset which requires 3.8? We're currently
sitting on 3.7 on a managed platform so can't pip install. Can the version
requirement be lowered?

**Comment by dirkroorda** [comment]
I'll see what I can do.
No doubt it will be possible, and not to much work.
Monday hopefully.

**Comment by dirkroorda** [comment]
I neede to check the following not to occur in the code:

* the walrus operator `:=`
* self documenting f-strings `=}`

And then I can lower the requirements to 3.7

**Comment by dirkroorda** [comment]
@jamespstrachan I just uploaded a new version of Text-Fabric, 8.5.13, with no changes except that the Python version requirement is back to 3.6.3.

**Comment by jamespstrachan** [comment]
Thanks Dirk!

I would understand if you wanted to use the syntactic niceness of walrus and f-strings, but until you feel the urge I'm happy that you keep the requirements as low as actually needed. Am happy to try to pull versions up at this end if you plan to go this way in future.

**Comment by dirkroorda** [comment]
Yes indeed, James.
I see very little use for the walrus operator.
Maybe in notebooks and other end-of-the-chain software, but not in packages and modules.
It is my intention keep the requirement at 3.6.3 for the foreseeable future.
