### ISSUE TITLE
Bug in fabric.py when trying to load Tischendorf text

### ISSUE THREAD

**Issue by haimeken** [annotation/text-fabric#73]
Hi, tonight I was trying to load Tischendorf text on a Jupyter notebook and I got the following message:

> Traceback (most recent call last):
>   File "/home/l/anaconda3/lib/python3.8/site-packages/tf/advanced/app.py", line 525, in findApp
>     app = appClass(
>   File "/home/l/anaconda3/lib/python3.8/site-packages/tf/advanced/app.py", line 314, in __init__
>     TF = Fabric(
>   File "/home/l/anaconda3/lib/python3.8/site-packages/tf/fabric.py", line 85, in __init__
>     module = module.strip("/").strip("\\")
> AttributeError: 'float' object has no attribute 'strip'
> Text-Fabric is not loaded

I was using Ubuntu 20.04 and a fresh TextFabric install.

This is how I was trying to load the module:

> from tf.app import use
> A = use('tisch', hoist=globals())

So, long story short, in order to solve it, I tracked the error and casted the float value I was getting to string in line 85 of fabric.py file. So, line 85 is now this way: 

> module = str(module).strip("/").strip("\\")

I don't know if somebody else is having the same problem, but after modifying that line I was able to load Tischendorf text.

I hope it helps.

Jaime

**Comment by dirkroorda** [comment]
Thanks @haimeken , I will look into it today (first dat after my holiday).

**Comment by dirkroorda** [comment]
@haimeken OK, got it.
What I did eventually is

```
            module = [str(x) for x in modules]
```

(two lines before).
And there were a few other places in the code that benefit from a change like this.
I will release the fix ASAP (meaning: today).

**Comment by dirkroorda** [comment]
@haimeken Fixed and released.

**Comment by haimeken** [comment]
Thank you @dirkroorda!
