### ISSUE TITLE
Bug in loading text-fabric 9.0

### ISSUE THREAD

**Issue by ch-jensen** [annotation/text-fabric#74]
When I load the TF-module, I get the following error message. I suspect it is a bug in version 9.0.

![billede](https://user-images.githubusercontent.com/17742225/129952673-bffb0776-1d9f-49de-8cad-2a6c3a854b55.png)

**Comment by dirkroorda** [comment]
Hi @ch-jensen I was on holiday. Will look at it today.

**Comment by dirkroorda** [comment]
Hi @ch-jensen (Christian), I see. I use a Python construct that has been introduced in Python 3.8, while I promised that Text-Fabric would be compatible with all pythons > 3.6.3. In 3.8 you can say things like 

``` python
x = 1
print(f"this is {x + 1=}") 
```

and it will print  

```
this is x + 1=2
```

Handy for debugging.
But: I should not break this kind of promise and I will remedy it ASAP.

**Comment by dirkroorda** [comment]
@ch-jensen Fixed and released.

**Comment by ch-jensen** [comment]
Thanks, @dirkroorda! It works well on my side now.
