### ISSUE TITLE
bug with the relational operators `<` and `>` when doing feature comparisons `.f<g.` or `.f>g.`

### ISSUE THREAD

**Issue by oliverglanz** [annotation/text-fabric#75]
#### When it functions correctly:
Lets take a clause in which we want  word2 to follow word1 I can define that relation by writing:
```
clause
  w1:word sp=verb
  w2:word lex=>LHJM/
w1 < w2
```
![image](https://user-images.githubusercontent.com/8409738/142433307-776401ff-4458-405a-9dd9-cd76930f70d0.png)

This makes one assume that `<`  means "follows in the order or sequence" (1-2-3-4): 2 follows 1.

#### When it does not function correctly
When I use `<` in the function of value comparison `.f<g.` it appears to function differently. Let me give an example:

I want to find clause number 2 and within that clause number 2 I want to find phrase number 1. Of course, I could simply write:
```
clause number=2
  phrase number=1
```
But - I thought - I could also write:
```
cl:clause number=2
   pr:phrase
cl .number>number. pr
```
I am assuming that this would mean that the number of cl must follow `>` the number of pr. And since the number that precedes 2 is 1, we would find phrase number=1. But that is not the case. Instead, I find phrase number=3:

![image](https://user-images.githubusercontent.com/8409738/142433750-32da94f1-0677-4837-96a4-72d85eae3c69.png)

Only if I reverse the relation defining line into `cl  .number<number. pr`  I get phrase number=1. But this would contradict how `<` functions elsewhere with the meaning "following" (in this case "greater" than the number of cl).

**Comment by dirkroorda** [comment]
Thanks @oliverglanz , indeed it is a bug.
Thanks for reporting it. There is a clear cause for it and it has now been fixed, in the latest version of Text-Fabric, 9.1.6.
