### ISSUE TITLE
No more app-xxx repositories

### ISSUE THREAD

**Issue by dirkroorda** [annotation/text-fabric#77]
When somebody creates a new text-fabric resource, and want to publish it as an app, a repository `app-xxx` must be created under the github organization `annotation`.
With a limited amount of existing tf corpora this was not a bad idea, but there are several disadvantages to this approach.

1. It is an extra hoop for a corpus developer to jump through.
2. It is an extra repository to maintain.
3. It is highly interdependent on the repository that holds the corpus data
4. It creates a dependency on a central entity, namely the annotation organization on github.

So I propose to move away from this approach in a gentle way.

Here is a proposal for the new approach

1. A TF-app is currently the contents of the `code` directory in a repo named `app-xxx` under annotation
2. We move this code directory to the repository of the repo that holds the tf-data, and we rename it to `app`.
3. We modify the `use()` command as follows. We examine the first argument. If it has no `/` in it, text-fabric will still look for an `app-xxx` repo in the `annotation` organization. But if its value does have `/` in it, text-fabric will use it to locate a TF-app.
4. `use("etcbc/bhsa")` will instruct text-fabric to look for organization `etcbc` on github, and within that for repo `bhsa` and within that for directory `app`.
5. I will migrate all existing `app-xxx` under annotation to `app` directories in their corresponding tf data repositories.
6. To retain backwards compatibility, I will add some sort of redirect directive to the old `app-xxx repos`. So `use("bhsa")` will still work, but the user gets a warning that he should use `use("etcbc/bhsa")` in the future.
7. If you do not intend to load a tf-app, but just tf feature data, you can say `use(None, data="x/y/z")`

**Comment by oliverglanz** [comment]
Your proposal seems to be the way to go. Indeed, to think of keeping two repositories well synced is an additional step to think of and spend time on. Your suggestion also allows for fewer app-name restrictions. Finally, annotations and etcbc do not have to invest additional resources in quality control for app repos they have not developed but are hosted under annotation or etcbc. So I am only supportive to your suggestion, Dirk.

**Comment by dirkroorda** [comment]
Good. I might change some details of the proposal when I get along, e.g. `use("data:x/y/z")` instead of `use(None, data="x/y/z")`.
And there is one complication that I have to deal with: the layeredsearch interfaces. Text-Fabric has a command `text-fabric-make` that creates a full-text search interface for a corpus. It is static HTML + Javascript and it is served by the GitHub Pages of the `app-xxx` repositories. Where shall I move the layered search to? If I put it in the main data repository of a corpus, it might interfere with the existing GitHub Pages of that repo. For example, the BHSA uses its Github pages for the feature documentation. It is possible to generate the layered search interface within the existing GitHub Pages, but that will create a nasty interference pattern in both the text-fabric-make command and the commands to generate the feature documentation. 

So I think I need separate repos for the layered search interfaces. Instead of `annotation/app-bhsa` I could make `etcbc/bhsa-search`. Then the repo is still in the same organization as the main repo.

**Comment by dirkroorda** [comment]
Done. In the process I also moved the layeredsearch interfaces in some annotation/app-corpus directories to org/corpus-search directories. And I moved the tutorials in annotation/tutorials/corpus to org/corpus/tutorial.

The effect is that you can do all of your corpus work in TF in your own organization and repo, without needing help from me for adjusting things in annotation.

**Comment by dirkroorda** [comment]
It is in text-fabric 9.2.0

See this documentation: https://annotation.github.io/text-fabric/tf/app.html
